name: animal_voice_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8         # iOS style icons

  get: ^4.7.2                     # State management and navigation

  provider: ^6.1.5                # Another state management package

  dio: ^5.8.0+1                   # For making HTTP requests

  shared_preferences: ^2.5.3      # For saving simple data locally

  just_audio: ^0.10.4             # For playing audio files

  cached_network_image: ^3.4.1    # For loading and caching images from the internet

  audioplayers: ^6.5.0            # Another audio player package

  flutter_cache_manager: ^3.4.1    # For caching images from the internet

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  # To add assets in application
  assets:
    - assets/
